language: go
  
jobs:
  include:
    - os: linux
      dist: xenial
      arch: amd64
    - os: linux
      dist: xenial
      arch: arm64
    - os: linux
      dist: xenial
      arch: arm64-graviton2
      virt: lxd
      group: edge
    - os: linux
      dist: xenial
      arch: ppc64le
    - os: linux
      dist: xenial
      arch: s390x
    - os: linux
      dist: bionic
      arch: amd64
    - os: linux
      dist: bionic
      arch: arm64
    - os: linux
      dist: bionic
      arch: arm64-graviton2
      virt: lxd
      group: edge
    - os: linux
      dist: bionic
      arch: ppc64le
    - os: linux
      dist: bionic
      arch: s390x
    - os: osx
      osx_image: xcode12.2
    - os: windows

go:
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - "master"

notifications:
  email:
    on_success: never
    on_failure: always
